version: "3.8"

services:
  db:
    image: postgres
    container_name: event-mgmt-postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - db.env
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - event-mgmt-network

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    container_name: event-mgmt-pgadmin
    restart: always
    ports:
      - "8888:80"
    env_file:
      - db.env
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - event-mgmt-network

volumes:
  db_data:
  pgadmin_data:
    driver: local

networks:
  event-mgmt-network:
    driver: bridge