# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: appleboy/ssh-action@v0.1.2
      with:
        host: ${{secrets.SSH_HOST}}         # Remote IP
        key: ${{secrets.SSH_KEY}}           # Private key
        username: ${{secrets.SSH_USERNAME}} # Username
        script: |
          mkdir -p ~/apps/event-mgmt-core
          cd ~/apps/event-mgmt-core
          git clone git@github.com:BEOpenSourceCollabs/EventManagementCore.git
          echo 'Successfully deployed to remote server'
