# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: cross-the-world/ssh-pipeline@v1.2.0
      with:
        host: ${{secrets.SSH_HOST}}
        key: ${{secrets.SSH_KEY}}
        user: ${{secrets.SSH_USERNAME}}
        script: |
          mkdir -p ~/apps/event-mgmt-core
          cd ~/apps/event-mgmt-core
          git clone git@github.com:BEOpenSourceCollabs/EventManagementCore.git
          echo 'Successfully deployed to remote server'
